name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">= 1.20.1"
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -E misspell
      - name: Test
        run: make vet test
